services:

  spark-master:
    container_name: spark-master
    build: .
    image: spark-image
    entrypoint: ["./provision.sh", "master"]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 5s
      retries: 3
    env_file:
      - .env.spark
    volumes:
      - ./spark_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-ivy:/opt/spark/ivy-cache
      - spark-logs:/opt/spark/spark-events
    ports:
      - "8080:8080" # Frontend
      - "7077:7077" # Backend

  spark-worker:
    container_name: spark-worker
    build: .
    image: spark-image
    entrypoint: ["./provision.sh", "worker"]
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - ./spark_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-ivy:/opt/spark/ivy-cache
      - spark-logs:/opt/spark/spark-events
    ports:
      - "8081:8081"

  spark-history:
    container_name: spark-history
    build: .
    image: spark-image
    entrypoint: ["./provision.sh", "history"]
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - spark-ivy:/opt/spark/ivy-cache
      - spark-logs:/opt/spark/spark-events
    ports:
      - "18080:18080"
  
  spark-developer:
    container_name: spark-developer
    build: .
    image: spark-image
    entrypoint: ["/bin/bash"]
    stdin_open: true
    tty: true
    depends_on:
      - spark-master
      - spark-worker
    volumes:
      - ./spark_apps:/workspace/spark_apps:cached
      - ./spark_data:/workspace/spark_data:cached
      - ./spark_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-ivy:/opt/spark/ivy-cache
      - spark-logs:/opt/spark/spark-events

  spark-notebook:
    container_name: spark-notebook
    build: .
    image: spark-image
    working_dir: /opt/spark/notebooks
    entrypoint: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
    depends_on:
      - spark-master
      - spark-worker
    ports:
      - "8888:8888"
    volumes:
      - ./spark_notebooks:/opt/spark/notebooks
      - ./spark_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-ivy:/opt/spark/ivy-cache
      - spark-logs:/opt/spark/spark-events

  spark-driver:
    container_name: spark-driver
    build: .
    image: spark-image
    entrypoint: ["/bin/bash"]
    stdin_open: true
    tty: true
    depends_on:
      - spark-master
      - spark-worker
    volumes:
      - ./spark_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-ivy:/opt/spark/ivy-cache
      - spark-logs:/opt/spark/spark-events

volumes:
  spark-logs:
  spark-ivy: