spark.eventLog.enabled true
spark.eventLog.dir file:///opt/spark/spark-events
spark.history.fs.logDirectory file:///opt/spark/spark-events
spark.sql.extensions io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog org.apache.spark.sql.delta.catalog.DeltaCatalog
spark.jars.ivy /opt/spark/ivy-cache
spark.executorEnv.PYARROW_IGNORE_TIMEZONE 1
